[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cedar"
version = "0.1.0"
description = "A raster simulation and optimisation library"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    {name = "Mushthafa Sinuhaji"}
]

dependencies = [
    "numpy",
    "numba",
    "vispy"
]